# This is a config for E2B sandbox template.
# You can use 'template_id' (pkhwlfaa7bhuq6o5hgs4) or 'template_name (zapier-js-sandbox) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='zapier-js-sandbox')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'zapier-js-sandbox' })

dockerfile = "e2b.Dockerfile"
template_name = "zapier-js-sandbox"
template_id = "pkhwlfaa7bhuq6o5hgs4"
