# This is a config for E2B sandbox template.
# You can use 'template_id' (dal9bti7o0pqx3236xfm) or 'template_name (zapier-ts-sandbox) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='zapier-ts-sandbox')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'zapier-ts-sandbox' })

dockerfile = "e2b.Dockerfile"
template_name = "zapier-ts-sandbox"
template_id = "dal9bti7o0pqx3236xfm"
