# This is a config for E2B sandbox template.
# You can use 'template_id' (sdpfw919f59yif7qkiw6) or 'template_name (zapier-python-sandbox) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='zapier-python-sandbox')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'zapier-python-sandbox' })

dockerfile = "e2b.Dockerfile"
template_name = "zapier-python-sandbox"
template_id = "sdpfw919f59yif7qkiw6"
