# This is a config for E2B sandbox template.
# You can use 'template_id' (eq85s3jm91thssj6h0sz) or 'template_name (zapier-python-sandbox-2) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='zapier-python-sandbox-2')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'zapier-python-sandbox-2' })

start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_name = "zapier-python-sandbox-2"
template_id = "eq85s3jm91thssj6h0sz"
